#链接bus-kafka
spring: 
  cloud: 
    bus: 
      enabled: true
    trace: 
      enabled: true
##########stream 消息驱动配置##########
##########stream 消息发送输出通道配置##########
    stream: 
      bindings: 
        iot_output: 
          destination: iot-push-message-topic
          content-type: text/plain
###iot 烟感消息###
        iot_smokealarm_output: 
          destination: iot-push-smokealarm-message-topic
          content-type: text/plain
  kafka: 
    bootstrap-servers: afkafka.com:9092


