#链接kafka
spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: pmsconfigclient
        uri: lb://pmsconfigclient
        predicates:
        - Path= /client/**
      - id: pmsauth
      uri: lb://pmsauth
      predicates:
      - Path= /auth/**
  kafka:
    bootstrap-servers: afkafka.com:9092
