#链接kafka
spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: pmsconfigclient
        uri: lb://pmsconfigclient
        predicates:
        - Path= /client/**
      - id: pmsauth
      uri: lb://pmsauth
      predicates:
      - Path= /auth/**
  kafka:
    bootstrap-servers: afkafka.com:9092
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9004/auth/oauth/token
      user-authorization-uri: http://localhost:9004/auth/oauth/authorize
      id: web
    resource:
      user-info-uri: http://localhost:9004/auth/api/member
      prefer-token-info: false
