#链接kafka
spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: pmsconfigclient
        uri: lb://pmsconfigclient
        predicates:
        - Path= /**/**
  kafka:
    bootstrap-servers: afkafka.com:9092

test: 1
