#链接kafka
spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: pmsconfigclient
        uri: lb://pmsconfigclient
        predicates:
        - Path= /client/**
      - id: pmsauth
        uri: lb://pmsauth
        predicates:
        - Path= /auth/**
  kafka:
    bootstrap-servers: afkafka.com:9092
    

#---------------------OAuth2---------------------
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9005/oauth/token
      user-authorization-uri: http://localhost:9005/oauth/authorize
      id: web
    resource:
      user-info-uri: http://localhost:9005/auth/api/member
      prefer-token-info: false

#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
    
white: 
  ips: 
    list: 127.0.0.1,0:0:0:0:0:0:0:1

