#链接kafka
spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: pmsconfigclient
        uri: lb://pmsconfigclient
        predicates:
        - Path= /client/**
  kafka:
    bootstrap-servers: afkafka.com:9092
    

#---------------------OAuth2---------------------
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9004/auth/oauth/token
      user-authorization-uri: http://localhost:9004/auth/oauth/authorize
      id: web
    resource:
      user-info-uri: http://localhost:9004/auth/api/member
      prefer-token-info: false

#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3500
