#链接kafka
spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  kafka:
    bootstrap-servers: afkafka.com:9092
    
zuul: 
  retryable: false
  ignoredServices: *
  host: 
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  add-proxy-headers: true
  routes: 
    fungame-pay-api:
      stripPrefix: false
    pmsauth: 
      path: /auth/**
      serviceId: pmsauth
      sensitiveHeaders: *
    pmsconfigclient: 
      path: /client/**
      serviceId: pmsconfigclient
      sensitiveHeaders: *  

#---------------------OAuth2---------------------
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9004/auth/oauth/token
      user-authorization-uri: http://localhost:9004/auth/oauth/authorize
      id: web
    resource:
      user-info-uri: http://localhost:9004/auth/api/user
      prefer-token-info: false

#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
    
white: 
  ips: 
    list: 127.0.0.1,0:0:0:0:0:0:0:1

